### ISSUE TITLE
Cocoapod for 1.6.10

### ISSUE THREAD

**Issue by AnthonyWard** [CAAPIM/iOS-MAS-Foundation#164]
Could you please add pods for version 1.6.10 for:

MASUI
MASConnecta
MASIdentityManagement
MASStorage
MASFoundation

**Comment by BobbyWeber** [comment]
All 1.6.10 Cocoapods have already been released with the 1.6.00 release.
If you remove or change the pod version in your podfile it will grab the latest of the specified version.
Please check your podfile and either update the version to 1.6.10 or removed the version for the latest as shown.
![cocoapodspodfile](https://user-images.githubusercontent.com/17500765/40997676-5f141c4a-68ba-11e8-9404-4320a662144b.png)
Once that is done do a pod update or if that fails do a pod install.
Also please ensure you are on the latest xcode and the latest cocoapod version.
![1 6 10cocoapods](https://user-images.githubusercontent.com/17500765/40997707-6bf3eda0-68ba-11e8-9a45-63b311e10d6f.png)
