### ISSUE TITLE
CA Mobile SDK (MAG/MAS) - SNI Client Support

### ISSUE THREAD

**Issue by MarlosChida** [CAAPIM/iOS-MAS-Foundation#169]
This is not an issue, just a question.

We are implementing MAS/MAG/RAS SDK at a customer, and to fulfill some networking infrastructure requirements (Firewall/WAF/Reverse Proxy...) our customer is asking if the "Mobile SDK for CA Mobile API Gateway" (https://mas.ca.com) supports SNI (Server Name Indication).

We couldn't find this information in the official documentation.

By our searches in the Official Documentation and CA Communities site, we believe that CA API Gateway (Server) does not have SNI support, but the question above is specific for the Mobile Client SDK (Android/iOS/etc).

SNI can be described as:

SNI stands for Server Name Indication and is an extension of the TLS protocol. It indicates which hostname is being contacted by the browser (client) at the beginning of the 'handshake'-process.
This allows a server to present multiple certificates on the same IP address and TCP port number and hence allows multiple secure websites to be served off the same IP address without requiring all those sites to use the same certificate.

What we want to know is:

In the above scenario (SNI-enabled server serving multiple HTTPS hosts), if a client using MAS SDK connects to this server, it will, during TLS handshake, provide server name information to the server, which, in turn, will present the righ SSL certificate to the SDK?

Meaning "does MAS SDK HTTP(S) Client Libraries supports and uses SNI by default?"

If the Mobile Client SDK supports SNI, we need to know if there is any limitation.

We already got an answer for the same question for the Android SDK (https://github.com/CAAPIM/Android-MAS-SDK/issues/268)

Best Regards,

Marlos Chida

**Comment by jhoongo** [comment]
Hi Marlos,

By default, if you are using iOS SDK, the SDK will validate the domain name of the certificate with the host that it is trying to reach.

You can refer to the actual implementation where it is creating the server trust with the domain name if validateDomainName is set to true (which is by default).
https://github.com/CAAPIM/iOS-MAS-Foundation/blob/Stable/MASFoundation/Classes/_private_/services/network/internal/MASSecurityPolicy.m#L64

Please let me know if you have any further question or concern.

Thanks,

**Comment by MarlosChida** [comment]
Hi,

   I think you misunderstood my question. My question is if the HTTP Client libraries used by the SDK are SNI compliant.

   When a request is made to a SNI-enabled server that hosts multiple HTTPS domains, the client must inform, during TLS handshake, the server name so the server can present the right SSL certificate corresponding to the domain accessed.

   Client validation occurs after this part of the handshake.

   I kindly ask you to read again the  SNI description and the information my customer seeks in my original post.

Thanks again,

Marlos Chida

**Comment by jhoongo** [comment]
Hi Marlos,

Please find the below answer from Apple's official.
https://forums.developer.apple.com/message/318662#318662

iOS MASFoundation's underlying network protocol is using NSURLSession, which according to Apple's official confirmed that NSURLSession, by default, will always use the host from the request URL for the SNI.

Please let me know if you have any further question or concern.

Thanks,

**Comment by MarlosChida** [comment]
Hi,

   That was exactly the answer I was looking for.
   Thank you very much for your attention. 

Marlos  Chida
