### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by adrianod1as** [CAAPIM/iOS-MAS-Foundation#192]
Hi,

Would it be possible to add [Carthage](https://github.com/Carthage/Carthage) support?

Thanks

**Comment by jhoongo** [comment]
Hi,

Unfortunately, we currently do not support Carthage for the SDK.
We currently only support Cocoapods which can be found in [here](https://cocoapods.org/pods/MASFoundation).

If you are a customer, or employee of CA Technologies, and would like to officially request this Carthage support, please send us the feature request on CA Community forum under MAG.

Thanks,
