### ISSUE TITLE
Question: Set global requests connect and read timouts

### ISSUE THREAD

**Issue by MarlosChida** [CAAPIM/iOS-MAS-Foundation#193]
Greetings,

   In Android MAS SDK It's possible to set requests connect and read timeouts globally, using something like this:
<code>
        MAS.setConnectionListener(new MASConnectionListener() {<p>
            @Override<p>
            public void onObtained(HttpURLConnection connection) {<p>
                connection.setConnectTimeout(2000);<p>
                connection.setReadTimeout(2000);<p>
            }<p>
       }
</code>

Using this code, implicit requests (like initialize, register, login...) also use this timeout values. Is it possible to achieve the same behavior  in iOS MAS SDK?

**Comment by jhoongo** [comment]
Hi,

Unfortunately, in iOS SDK, we currently do not support timeout configuration for requests.
By default, iOS SDK adhere global timeout setting which is 60 seconds for all request.

If you are a customer, or employee of CA Technologies, and would like to officially request for support of this feature, please send us a new feature request through CA Community channel.

Thanks,
