### ISSUE TITLE
How to send JSON Array in request body?

### ISSUE THREAD

**Issue by rodrigosol** [CAAPIM/iOS-MAS-Foundation#194]
Hello,
I have to send a json array inside the request body.

It seems the MASRequest body attribute only accepts a dictionary.

How can I accomplish that?

I was able to do that effortless on Android SDK.

Thanks

**Comment by rodrigoareis** [comment]
Hello Rodrigo,

the type NSDictionary allows developers to pass multiple parameters in the request body. 

You did not provide any information where you keep the JSON Array, let's assume you have it as string, but you could also obtain it from a file, another request, and so on.

```objc
// A JSON Array
NSString *jsonArrayString = @"[{ \"color\":\"Red\" },{ \"color\":\"Blue\" },{ \"color\":\"Yellow\"}]";
NSLog(@"jsonArrayString=%@", jsonArrayString);
```

In the Objective C sample bellow, we are passing a JSON Array along with another parameter

```objc
//
// Example 1 - multiple parameters in the body
//

// Building your request, Json Array along with other parameter
MASRequest *request1 = [MASRequest postTo:^(MASRequestBuilder *builder) {
    builder.endPoint = @"/your/endpoint";
    builder.responseType = MASRequestResponseTypeTextPlain;
    builder.body = @{@"id":@"someid", @"json":jsonArrayString};
}];
NSLog(@"request1.body=%@", request1.body);
```

From your question, it is not clear if the JSON Array will be a single parameter in the body, but if it is the case and you want to parse it to NSDictionary, you could use NSJSONSerialization as shown in the second sample bellow.

```objc
//
// Example 2 - single parameter in the body
//

// Parsing jsonArray
NSDictionary *jsonDictionary = [NSJSONSerialization
                                JSONObjectWithData:[jsonArrayString dataUsingEncoding:NSUTF8StringEncoding]
                                options:kNilOptions
                                error:nil];
NSLog(@"jsonDictionary=%@", jsonDictionary);

// Building your request, only the Json Array in the body
MASRequest *request2 = [MASRequest postTo:^(MASRequestBuilder *builder) {
    builder.endPoint = @"/your/endpoint";
    builder.responseType = MASRequestResponseTypeTextPlain;
    builder.body = jsonDictionary;
}];
NSLog(@"request2.body=%@", request2.body);
```

Please, let us know if you have any further question.
