### ISSUE TITLE
Unable to login using MASUser from MASFoundation.

### ISSUE THREAD

**Issue by jordanboaz** [CAAPIM/iOS-MAS-Foundation#234]
**MASFoundation 1.9.00**

**What is happening**
I am trying to login a user using the MAS SDK. 

I am using the function loginWithUserName from the MASUser.

When I try to login, my app crashes and I get the following debug output:

*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[_NSZeroData subdataWithRange:]: range {1, 18446744073709551615} causes integer overflow'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23b98bde __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff503b5b20 objc_exception_throw + 48
	2   Foundation                          0x00007fff255ddb3c -[NSData(NSData) writeToFile:options:error:] + 0
	3   MASFoundation                       0x000000010e7a1557 -[MASASN1Decoder parseWithRange:] + 2359
	4   MASFoundation                       0x000000010e7a0be8 -[MASASN1Decoder decodeASN1] + 216
	5   MASFoundation                       0x000000010e6e7d61 -[MASDERCertificate parseCertificateData] + 257
	6   MASFoundation                       0x000000010e7a57ce -[MASDevice(MASPrivate) saveWithUpdatedInfo:] + 1470
	7   MASFoundation                       0x000000010e748152 __63-[MASAuthCredentials(MASPrivate) registerDeviceWithCredential:]_block_invoke + 1474
	8   MASFoundation                       0x000000010e730679 __147-[MASNetworkingService sessionDataTaskCompletionBlockWithEndPoint:parameters:headers:httpMethod:requestType:responseType:isPublic:completionBlock:]_block_invoke + 8633
	9   MASFoundation                       0x000000010e7b057f __67-[MASURLSessionManager dataOperationWithRequest:completionHandler:]_block_invoke + 255
	10  MASFoundation                       0x000000010e77f1e8 __68-[MASSessionDataTaskOperation URLSession:task:didCompleteWithError:]_block_invoke.419 + 104
	11  libdispatch.dylib                   0x000000010e9a7df0 _dispatch_call_block_and_release + 12
	12  libdispatch.dylib                   0x000000010e9a8d64 _dispatch_client_callout + 8
	13  libdispatch.dylib                   0x000000010e9b6b11 _dispatch_main_queue_callback_4CF + 721
	14  CoreFoundation                      0x00007fff23afb699 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	15  CoreFoundation                      0x00007fff23af62f9 __CFRunLoopRun + 2329
	16  CoreFoundation                      0x00007fff23af56b6 CFRunLoopRunSpecific + 438
	17  GraphicsServices                    0x00007fff3815cbb0 GSEventRunModal + 65
	18  UIKitCore                           0x00007fff47162a67 UIApplicationMain + 1621
	19  rnt                                 0x000000010d569d10 main + 112
	20  libdyld.dylib                       0x00007fff5123bcf5 start + 1
	21  ???                                 0x0000000000000001 0x0 + 1

**What should happen**
The sdk should login correctly and return a MASUser object.

_Does_ anyone know how to fix this?_

**Comment by maclacerda** [comment]
Same problem here, I'm using the `MASFoundation` version `1.9.00` in my `Podfile`

**Comment by ysd24** [comment]
This issue is fixed in 1.9.20 and later builds.

**Comment by maclacerda** [comment]
Thanks, work for me `1.9.20`

**Comment by mahithegeek** [comment]
Closing issue as the latest release fixed the problem
