### ISSUE TITLE
Fix CocoaPods - Published PodSpec should include other MASFoundation headers

### ISSUE THREAD

**Issue by jsm174** [CAAPIM/iOS-MAS-Foundation#30]
The current published CocoaPod for MASFoundation is 1.2.01 and only includes references to MASFoundation.h:

https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/0/b/8/MASFoundation/1.2.01/MASFoundation.podspec.json

If you add "MASFoundation" to the podfile when using the MASStarter template

```
target 'MASStarter' do
 use_frameworks!
 pod 'DGActivityIndicatorView'
 pod 'SABlurImageViewObjc'
 pod 'SCLAlertView-Objective-C'
 pod 'MASFoundation'
end
```

you will get:

#import <MASFoundation/MAS.h>     'MASFoundation/MAS.h' file not found

![screen shot 2017-01-06 at 2 53 22 pm](https://cloud.githubusercontent.com/assets/1197137/21730912/f2a6e0e0-d41f-11e6-816d-3da58b6f0972.png)

**Comment by lsanches** [comment]
Jason,

currently our SDK do not support cocoapods. This is in our ToDo list to be addressed soon.

Thanks,

Luis Sanches

**Comment by lsanches** [comment]
Hi Jason,

The iOS Mobile SDK is now available via cocoapods as well. For the moment we have two official releases: 1.2.03 and 1.3.01

Please go ahead and give it a trial. 

Thanks for your feedback.

**Comment by jsm174** [comment]
Awesome. I will check it out!
